### ISSUE TITLE
Thiết kế DB

### ISSUE THREAD

**Issue by mrq2000** [mrq2000/BTL_CNPM#1]
Thiết kế DB cho backend

**Comment by HieuPham2000** [comment]
Đây là thiết kế của tôi, t dùng MS SQL Server: 

![image](https://user-images.githubusercontent.com/61912505/99553433-b6c22a00-29f0-11eb-9dc9-96211c3dabbc.png)
![image](https://user-images.githubusercontent.com/61912505/99553492-c6da0980-29f0-11eb-96d8-025c10b8005f.png)
![image](https://user-images.githubusercontent.com/61912505/99553551-db1e0680-29f0-11eb-8c2c-82a1ec3b89df.png)
![image](https://user-images.githubusercontent.com/61912505/99553697-04d72d80-29f1-11eb-944c-73a12b6f2ec9.png)

**Comment by mrq2000** [comment]
Thiết kế DB theo dạng JSON đi ông. Cái của mình dùng NoSql nha.
Dạng như này này
users: {
  1: { name: 'QuocPham', request: {12: { content:"............"}}}
}

**Comment by HieuPham2000** [comment]
@mrq2000 

Tôi có thử viết cho role người dân:
https://jsoneditoronline.org/#left=cloud.66e3af5d977448039ea71791142e33b9

![image](https://user-images.githubusercontent.com/61912505/99874977-72b46c80-2c1e-11eb-89fa-4c47e0f06f3e.png)

Bro vào chỉnh sửa thêm nhé. Mà tôi chưa hiểu lắm, tất cả dữ liệu mình cho hết vào 1 chuỗi JSON luôn à, hay thông tin users, admin, thông tin các cơ quan thì mỗi cái viết thành 1 chuỗi JSON khác nhau?

**Comment by HieuPham2000** [comment]
> @mrq2000
> 
> Tôi có thử viết cho role người dân:
> https://jsoneditoronline.org/#left=cloud.66e3af5d977448039ea71791142e33b9
> 
> ![image](https://user-images.githubusercontent.com/61912505/99874977-72b46c80-2c1e-11eb-89fa-4c47e0f06f3e.png)
> 
> Bro vào chỉnh sửa thêm nhé. Mà tôi chưa hiểu lắm, tất cả dữ liệu mình cho hết vào 1 chuỗi JSON luôn à, hay thông tin users, admin, thông tin các cơ quan thì mỗi cái viết thành 1 chuỗi JSON khác nhau?

Tôi đã update demo hoàn chỉnh cho dữ liệu tại link trên rồi nhá
