### ISSUE TITLE
Làm rõ yêu cầu bài toán: Quản lý thông tin phản ánh, kiến nghị

### ISSUE THREAD

**Issue by HieuPham2000** [mrq2000/BTL_CNPM#10]
### Bối cảnh bài toán: 
Ban quản lý tổ dân phố 7 phường La Khê cần xây dựng một phần mềm quản lý thông tin khu dân cư / tổ dân phố. Tổ dân phố 7 có hơn 400 hộ gia đình với 1.700 nhân khẩu, chưa kể hàng trăm sinh viên thuê trọ và hàng chục gia đình nơi khác đến thuê nhà làm kinh doanh dịch vụ.
Địa bàn rộng, dân cư đông và phức tạp nên ban quản lý mong đợi phần mềm này có thể quản lý thông tin chung cả tổ dân phố từ biến động nhân khẩu, hộ khẩu đến các công tác đoàn thể khác. Ban quản lý gồm một tổ trưởng, một tổ phó và các cán bộ phụ trách các hoạt động nghiệp vụ khác. Tổ trưởng và tổ phó có thể thực hiện tất cả các nghiệp vụ quản lý, còn các cán bộ
khác phụ trách từng nghiệp vụ theo phân công cụ thể.

---
### Cụ thể: Quản lý thông tin phản ánh, kiến nghị

- Các thông tin phản ánh, kiến nghị của nhân dân trong tổ sẽ được tổ trưởng ghi nhận để tổng hợp gửi lên cấp trên. 

- Mỗi phản ảnh, kiến nghị cần ghi nhận: người phản ánh, nội dung, ngày phản ánh, phân loại và trạng thái.

- Khi có phản hồi từ các cơ quan có liên quan, tổ trưởng sẽ ghi nhận lại với phản ánh / kiến nghị tương ứng và
thông báo cho cá nhân có liên quan. 

- Các kiến nghị trùng nhau có thể được gộp lại thành một nhưng phải ghi nhận những người phản ánh và số lần phản ánh. 

- Hàng quý tổ trưởng cũng cần thống kê số lượng kiến nghị theo trạng thái (mới ghi nhận, chưa giải quyết, đã giải quyết,…)

**Comment by HieuPham2000** [comment]
Là tổ trưởng tổ dân phố, tôi muốn ghi nhận, cập nhật, thống kê các phản ánh, kiến nghị để dễ dàng giải quyết, thông báo cho các cá nhân liên quan và tổng hợp gửi lên cấp trên.

Yêu cầu chức năng:

- [x] Xem danh sách thông tin các kiến nghị, phản ánh

- [x] Gửi phản hồi cho người dân

- [x] Thống kê số lượng kiến nghị theo trạng thái giải quyết

- [x] Xem danh sách thông tin các cơ quan, tổ chức

**Comment by mrq2000** [comment]
LGTM

**Comment by tungnk181120** [comment]
Nguyễn Kim Tùng
SĐT: 0332458363
Địa chỉ: Cổ Loa, Đông Anh, Hà Nội.


Vào Th 4, 25 thg 11, 2020 vào lúc 17:14 Phạm Trung Hiếu <
notifications@github.com> đã viết:

**Comment by mrq2000** [comment]
CLOSED!
