### ISSUE TITLE
User Request

### ISSUE THREAD

**Issue by mrq2000** [mrq2000/BTL_CNPM#11]

**Comment by tungnk181120** [comment]
![userrequest](https://user-images.githubusercontent.com/72078935/102008478-72ae1500-3d63-11eb-9b91-4e9c205d42b6.png)

**Comment by tungnk181120** [comment]
![sendrequest](https://user-images.githubusercontent.com/72078935/102008514-c0c31880-3d63-11eb-9294-a3d49413d40f.png)

**Comment by HieuPham2000** [comment]
OK

**Comment by HieuPham2000** [comment]
CLOSED!
