### ISSUE TITLE
Update Info user + admin

### ISSUE THREAD

**Issue by mrq2000** [mrq2000/BTL_CNPM#12]

**Comment by EdwardNgo** [comment]
![Screenshot from 2020-12-13 16-06-44](https://user-images.githubusercontent.com/44334291/102007714-05e44c00-3d5e-11eb-8604-796352f55a05.png)

**Comment by EdwardNgo** [comment]
![user](https://user-images.githubusercontent.com/44334291/102007834-d84bd280-3d5e-11eb-88b1-ab3479cc43cc.png)
