### ISSUE TITLE
Thiết kế giao diện

### ISSUE THREAD

**Issue by mrq2000** [mrq2000/BTL_CNPM#2]

**Comment by HieuPham2000** [comment]
Theo bản thiết kế giao diện của Tùng thì mình tạm chia ra các screen:

1. Đăng nhập: chia 2 role, dành cho người dân và dành cho tổ trưởng

2. (Role Tổ trưởng) 
- Thông báo (có thể ở đây mình cho hiện các kiến nghị/hoặc phản hồi của các bên liên quan vừa gửi đến)
- Danh sách kiến nghị: Hiện danh sách tất cả kiến nghị (dạng table, ấn vào sẽ ra chi tiết) và có nút gửi phản hồi cho người dân hoặc chuyển ý kiến cho cơ quan tổ chức giải quyết
- Thống kê kiến nghị: cho chọn quý, chọn năm => thống kê, biểu đồ
- Thông tin các bên liên quan: Hiện thông tin 1 số cá nhân, tổ chức để liên lạc khi cần giải quyết kiến nghị
- Thông tin tài khoản

3. (Role Người dân)
- Thông báo
- Gửi ý kiến kiến nghị: Có form gồm tiêu đề, nội dung và file đính kèm
- Xem danh sách kiến nghị đã gửi và tình trạng giải quyết
- Xem thông tin tổ trưởng tổ dân phố hiện tại 
- Thông tin tài khoản

**Comment by HieuPham2000** [comment]
Tôi có thiết kế wireframe trên figma, anh em thảo luận góp ý thêm: 
[link-figma-giao-dien](https://www.figma.com/file/ymI4lUqrH5E8qCEAMsVWtX/Nh%E1%BA%ADp-m%C3%B4n-CNPM-Qu%E1%BA%A3n-l%C3%BD-ph%E1%BA%A3n-%C3%A1nh-ki%E1%BA%BFn-ngh%E1%BB%8B?node-id=9%3A198)
[link-drive-screenshot-giao-dien](https://drive.google.com/drive/u/1/folders/1iiGDK9jyaItprkUGSnkqwFzTb03o3XFE)

![Người dân - Chi tiết kiến nghị đã gửi](https://user-images.githubusercontent.com/61912505/99403475-1818c900-291d-11eb-8a48-ed332601eab6.png)

![Người dân - Danh sách kiến nghị đã gửi](https://user-images.githubusercontent.com/61912505/99403490-1b13b980-291d-11eb-9dd7-5233d3d66630.png)

**Comment by HieuPham2000** [comment]
Ae xem thử prototype - demo hoạt động của phần mềm: [Link-prototype](https://www.figma.com/proto/ymI4lUqrH5E8qCEAMsVWtX/CNPM-Nh%C3%B3m-18?node-id=12%3A81&viewport=236%2C165%2C0.06789010018110275&scaling=scale-down)
Ae mở link, nhấn phím z để fit màn hình. Sau đó thử nhấn vào các button tại mỗi screen để xem điều hướng giữa các screen

**Comment by mrq2000** [comment]
Đep đấy bro, còn phần login tôi chưa thấy.

**Comment by HieuPham2000** [comment]
> Đep đấy bro, còn phần login tôi chưa thấy.

Login bro làm như này là ổn rồi đấy

![125425412_210106213958000_1153778233490891987_n](https://user-images.githubusercontent.com/61912505/99865878-5b09c380-2bdf-11eb-9941-fe7839ba794d.png)

**Comment by mrq2000** [comment]
CLOSED!
