### ISSUE TITLE
Thiếu LOGO

### ISSUE THREAD

**Issue by mrq2000** [mrq2000/BTL_CNPM#33]
Ông design, xong đẩy cái logo vào chỗ có chữ có LOGO cho tôi

**Comment by HieuPham2000** [comment]
![logo hn-khuevancac](https://user-images.githubusercontent.com/61912505/102008330-2ca48180-3d62-11eb-8a7a-01557462c048.jpg)

**Comment by HieuPham2000** [comment]
![image](https://user-images.githubusercontent.com/61912505/102009352-8197c600-3d69-11eb-996e-9480e6dc8f8d.png)
Thế này ổn chưa bro

**Comment by HieuPham2000** [comment]
![image](https://user-images.githubusercontent.com/61912505/102009380-a4c27580-3d69-11eb-93c6-184e025fc0c0.png)
![image](https://user-images.githubusercontent.com/61912505/102009390-ac821a00-3d69-11eb-9484-f89011dee3c1.png)

**Comment by HieuPham2000** [comment]
Nhưng có vấn đề là tôi phải để file logo.jpg ở  cùng folder với Header.js thì nó mới nhận đường dẫn. Tôi thử để trong assets/img rồi dùng đường dẫn '.../.../../assets/img/logo.jpg' thì nó không nhận

**Comment by HieuPham2000** [comment]
DONE. CLOSED
